# Generated by Django 5.0.7 on 2024-07-28 06:35

import django.db.models.deletion
import django_lifecycle.mixins
import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name Of Category')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('overview', models.CharField(max_length=500, verbose_name='Product Overview Message')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('warranty', models.TextField(blank=True, verbose_name='Product Warranty')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Amount On Discount')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Amount')),
                ('is_available', models.BooleanField(default=True, verbose_name='Product Available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='stores.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('image', models.ImageField(default=stores.models.get_default_pic, upload_to=stores.models.upload_to, verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='stores.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(max_length=100, verbose_name='Name Of SubCategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub_cats', to='stores.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
