# Generated by Django 5.0.7 on 2024-07-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='initial_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_amount',
        ),
    ]
