# Generated by Django 5.0.7 on 2024-07-28 09:48

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_initial_amount_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=stores.models.get_default_pic, upload_to=stores.models.upload_to, verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Amount'),
        ),
    ]
